---
fontsize: 12pt
lang: spanish
mainlang: spanish
other_langs:
    -   english
papersize: letterpaper
documentclass: report
geometry:
    -   inner=4cm
    -   outer=3cm
    -   vmargin=3cm
    -   twoside
mainfont: Times New Roman
institution: Universidad Técnica Federico Santa María
academic_unit: Departamento de Electrónica
city: Valparaíso
country: Chile
title: >
    Aplicación Móvil para Aprendizaje Activo en Aulas
    SCALE-UP
author: Cristóbal Edmundo Ganter Horst
degree: Ingeniero Civil Electrónico
professor: Werner Creixell
month: Enero
year: 2016
advertencia: true
numbersections: true
toc-depth: 1
agradecimientos: src/0-preambulo/agradecimientos.tex
dedicatoria: src/0-preambulo/dedicatoria.tex
resumen: src/0-preambulo/resumen.tex
abstract: src/0-preambulo/abstract.tex
definiciones: src/definiciones
bibliografia: src/bibliografia.tex
main_content:
    -   src/1-introduccion/introduccion.tex
    -   src/2-estado-del-arte/estado-del-arte.tex
    -   src/3-propuesta/propuesta.tex
    -   src/4-resultados/resultados.tex
    -   src/5-contribuciones/contribuciones.tex
    -   src/6-conclusiones/conclusiones.tex
anexos:
    -   src/anexos/anexoA.tex
...
